### ISSUE TITLE
Mcmmo party protection

### ISSUE THREAD

**Issue by LogGits** [rutgerkok/BlockLocker#10]
It would be awesome if players in an mcmmo party could make locks that only party members can use.

**Comment by LogGits** [comment]
I saw in the change logs something about this, how's this turning out? I'd love to see this feature added.

**Comment by LogGits** [comment]
#28 integration has some flaws in it.

@jensvh I was testing this feature, seems to work well. Just has an issue with using mcmmo parties that have more then 16 characters e.g. /bl 3 [TestingTesting012] as it doesn't let you define the mcmmo party.

**Comment by rutgerkok** [comment]
I've changed the maximum length to 25 when using the command - should be long enough. The last characters on the sign simply won't be visible, but it should still work.
