### ISSUE TITLE
No text and no protection

### ISSUE THREAD

**Issue by TheCiROMG** [rutgerkok/BlockLocker#102]
![image](https://user-images.githubusercontent.com/61605643/108647859-6e575400-7498-11eb-919b-246a8f1772c9.png)

When wanting to protect a chest, the text is not seen AND DO NOT PROTECT YOURSELF, it happened after using builds 470 onwards of Paper MC

**Comment by TheCiROMG** [comment]
https://github.com/PaperMC/Paper/issues/5218

**Comment by rutgerkok** [comment]
Thanks for reporting, looks like Paper fixed this!
