### ISSUE TITLE
SimpleClans Support

### ISSUE THREAD

**Issue by TheCiROMG** [rutgerkok/BlockLocker#107]
I request this small support for this plugin to make it easier for my users to share elements, such as chests, ovens, etc.

**Comment by TheCiROMG** [comment]
I found another error and it is that when I give permissions in SimpleClans to a user to build, that user who was allowed, loses access to their chest / ovens, etc.

**Comment by rutgerkok** [comment]
Should now be added. I haven't tested it yet, but if you want to do that, feel free to download it:

https://ci.codemc.io/job/rutgerkok/job/BlockLocker/27/
