### ISSUE TITLE
CMI Sign Edit - Bypass Sign Protection

### ISSUE THREAD

**Issue by rockitseven** [rutgerkok/BlockLocker#108]
Hello! I have the CMI Sign edit function on our server, where you can shift and right click to edit signs. This can be used to bypass the sign protections provided by blocklocker. Is this something which can be fixed? Because, I really don't want to negate the permission. Thank you in advance for the help! Love your plugin.

**Comment by rutgerkok** [comment]
It could be that CMI is not firing the SignChangeEvent, which would mean that BlockLocker cannot react. I cannot confirm this however, as I don't have access to CMI. You can try this:

https://github.com/rutgerkok/BlockLocker/issues/18#issuecomment-522268847

**Comment by rockitseven** [comment]
Fixed in recent update.
