### ISSUE TITLE
[Paper 1.16.5] [Bug] Players Can [Private] Sea Lanterns

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [rutgerkok/BlockLocker#109]
https://cdn.discordapp.com/attachments/663584713902129153/848388499383386132/unknown.png

blocklocker-1.9.2
git-Paper-562 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Note: I will not see replies.

**Comment by rutgerkok** [comment]
![afbeelding](https://user-images.githubusercontent.com/1462188/120111807-aa731280-c173-11eb-9d54-455460abafb8.png)


Cannot reproduce. Make sure that sea lanterns don't appear in your `plugins/BlockLocker/config.yml`.

**Comment by PiggiesGoSqueal** [comment]
I did. Also one of my players pointed out there was a pressure plate on top of the sea lantern- so it was protecting that not the sea lantern. 

Issue closed.
