### ISSUE TITLE
Automatic sign completion for doors

### ISSUE THREAD

**Issue by LogGits** [rutgerkok/BlockLocker#11]
You can't rightclick a door to add the blocklocker sign to the door. Could you add a way, whereby it cancels the interactevent or blockplaceevent and places its own sign. This way it would also work for rightclicking enchanting tables and trapdoors.

Love the plugin, keep up the great work.

**Comment by rutgerkok** [comment]
Yeah, that would be nice to have.

**Comment by OfficialAndyX** [comment]
Is there any news on this, people are complaining about it.

**Comment by rutgerkok** [comment]
Should now be fixed! Could anyone help testing this? Download:

https://www.dropbox.com/s/pdg1x5mr5o9afle/BlockLocker.jar?dl=0

**Comment by LogGits** [comment]
Cheers it works great!
