### ISSUE TITLE
Problem about not supporting with QuickShop

### ISSUE THREAD

**Issue by MusicTW** [rutgerkok/BlockLocker#111]
I can lock the chest which is chestshop
just like this
![image](https://user-images.githubusercontent.com/52475422/122634414-bb7ac800-d110-11eb-84dc-8e95acf05ef8.png)

**Comment by rutgerkok** [comment]
This sounds like something that ChestShop should implement. Either it should protect the chest itself (cancelling the BlockPlaceEvent or SignChangeEvent) or it should simply force you to protect the chest first using BlockLocker.

**Comment by Ghost-chu** [comment]
BlockLocker didn't check player have target block build permission, and this will allow players abuse  BlockLocker to lock anything that not protected by BL blocks, not only chestshop but also other plugins with self lock feature plugins.

**Comment by LaurenceBarnes** [comment]
As a user of both plugins, I'd be really grateful if you could fix that issue ^-^
