### ISSUE TITLE
Protection signs do not update the users name after a name change

### ISSUE THREAD

**Issue by baailey** [rutgerkok/BlockLocker#113]
Plugin version: 1.10
Server version: git-Tuinity-"2310a94" (MC: 1.17.1)

Have run into an issue where if a player protects a sign and then changes their name, the sign will not change and will instead change to '~baailey' (name example).  

I took a look at previous reports to see if anyone was having the same problem as me, and I saw the following said: "The latest version (1.10) uses a new way of storing UUIDs on the signs. So all old signs are converted to the new saving format."

The account I have tested on only joined the server 15 minutes ago and has only locked a sign whilst using version 1.10, if that is important. 

The server is on online mode as well. If there is further info you need, I'll answer as soon as possible, thanks.

**Comment by ThatOneTree** [comment]
+1

**Comment by rutgerkok** [comment]
Should be fixed from build 36 onwards - download at https://ci.codemc.io/job/rutgerkok/job/BlockLocker/36/
