### ISSUE TITLE
Ability to lock regular blocks

### ISSUE THREAD

**Issue by LogGits** [rutgerkok/BlockLocker#12]
When we were using lockette we used to allow locking of mobspawners and beacons using signs. Is there a way to do this using this plugin?

**Comment by rutgerkok** [comment]
Sure! You can add any material to the `protectableContainers` setting in the configuration file (plugins/BlockLocker/config.yml). Use `SPAWNER` for the mob spawner and `BEACON` for the beacon.

**Comment by LogGits** [comment]
Ah ok thanks. Also to make it a bit more intuitive maybe it should be changed to `ProtectableBlocks` instead of `protectableContainers`?
