### ISSUE TITLE
Right click on sign, editing via command and actual protection not working

### ISSUE THREAD

**Issue by olli991** [rutgerkok/BlockLocker#125]
I installed BlockLocker on a CraftBukkit server running 1.18.
It is running EssentialsX with all its plugins, LuckPerms, Vault and CoreProtect.

If I place a chest i get the info I could protect it.
If I crouch and place a sign it is not autofilling [Private] to it.
If I do it manually and save it it actually automatically adds my name to it.
But players can still acces my chest. 
I can also not right click on the sign to use the edit command with it.

All players have the blocklocker.protect permission set in LuckPerms.

What am I missing or doing wrong here?

Appreciate you help, thanks :-)

**Comment by rutgerkok** [comment]
Sorry, no idea what's going on here. Seems like the plugin is not recognizing the protection.

One thing to check would be that the plugin is set to English, and that in the language file `translations-en.yml` the `tag.private` is still set to `[Private]`.
