### ISSUE TITLE
Duplication of slimefun items

### ISSUE THREAD

**Issue by SideLo98** [rutgerkok/BlockLocker#129]
https://streamable.com/14s8f7

everything is latest version
![image](https://user-images.githubusercontent.com/67060780/148702446-46256565-4734-487a-960c-d96338c87f2a.png)

**Comment by Skizzles** [comment]
https://github.com/rutgerkok/BlockLocker/issues/121
Previous incident that was closed.

Further Details:
- Happens on Purpur, Paper, Spigot
- Happens on 1.17 and 1.18

**Comment by rutgerkok** [comment]
Just to make sure, are you using the latest dev build of BlockLocker? ( https://ci.codemc.io/job/rutgerkok/job/BlockLocker/ ) If not, could you test whether it's already fixed on there? (It should be, but I never got verification for this.)

**Comment by Skizzles** [comment]
@rutgerkok I tested this on both my servers and the dev build seems to resolve it.

Thank you

**Comment by Skizzles** [comment]
https://screenshots.skizzles.me/wAnA3/QoMEruNI79.mp4

^ video of it still happening

**Comment by SideLo98** [comment]
> Just to make sure, are you using the latest dev build of BlockLocker? ( https://ci.codemc.io/job/rutgerkok/job/BlockLocker/ ) If not, could you test whether it's already fixed on there? (It should be, but I never got verification for this.)

I tried this and still same: https://streamable.com/2xgw0l

**Comment by rutgerkok** [comment]
Oof, this was a difficult one, since the error originated in a completely unrelated place. But it should now be fixed. Thanks for reporting!

(Downloads at https://ci.codemc.io/job/rutgerkok/job/BlockLocker/ , build 52+)
