### ISSUE TITLE
Hopper Allows you to retrieve items from a chest in 1.18

### ISSUE THREAD

**Issue by Ilovelinux68** [rutgerkok/BlockLocker#130]
In 1.18 when a player puts a hooper under a chest blocked by another player, he still manages to get the items from the chest...This is very annoying!

**Comment by rutgerkok** [comment]
Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
> This isn't caused by BlockLocker, but it's caused by setting `hopper.disable-move-event` to `true` in your paper.yml file. If you set it back to `false`, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.

**Comment by Ilovelinux68** [comment]
Oh tank you 👍

**Comment by Ilovelinux68** [comment]
I hadn't read about spigot sorry
