### ISSUE TITLE
/bl <line> <playername> not working, message shown but nothing is updated

### ISSUE THREAD

**Issue by hkkongou** [rutgerkok/BlockLocker#131]
blocklocker 1.10.2
 This server is running Paper version git-Paper-150 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0c64d40)

use /bl 2 <player> command does not update chest sign username

https://user-images.githubusercontent.com/61608872/149498111-b9f42563-1737-4027-bb33-10570b4d2a93.mp4

**Comment by rutgerkok** [comment]
I think this was just fixed this a few days ago ( https://github.com/rutgerkok/BlockLocker/commit/b841beb855599a4d3edfaff64c15231d3c0afd16 ). You can help testing it at https://ci.codemc.io/job/rutgerkok/job/BlockLocker/
