### ISSUE TITLE
Sign Duplication Glitch

### ISSUE THREAD

**Issue by ItsSynchro** [rutgerkok/BlockLocker#132]
A sign protected door needs to be connected with a trapdoor, then start spam right clicking on the trapdoor, you'll get a "There's no protectable block nearby. (Shift-)right-click a container with a sign on your hard to protect it" and one more sign. 

https://www.youtube.com/watch?v=hSui6uOrhKw

Server Version: 1.17.1
Plugin Version: 1.10.3 (also tested with 1.10.2)

**Comment by MiunaPA** [comment]
I also have the same problem
https://youtu.be/TssU6QTinlA

Server Version: Paper 1.18.1-160
Plugin Version: 1.10.3

**Comment by KebabXL** [comment]
yh that same
https://youtu.be/j_zqsGdUIgM

Server Version: 1.18.1
Plugin Version: 1.10.3

**Comment by rutgerkok** [comment]
Thanks for reporting. There's still an underlying issue here (the plugin tries to place a [Private] sign when it should place a [More Users] sign), but the duplication glitch is at least fixed in build 54: https://ci.codemc.io/job/rutgerkok/job/BlockLocker/54/
