### ISSUE TITLE
Clicking on a fence gate with a sign will duplicate the sign

### ISSUE THREAD

**Issue by XiaoNiuC** [rutgerkok/BlockLocker#133]
As the title suggests, the sign can be replicated through a locked fence gate.

https://youtu.be/ydRLJFDUDE8

![擷取](https://user-images.githubusercontent.com/56481904/152035282-e592566e-81a2-42b5-95e0-70818a9288d0.PNG)

**Comment by rutgerkok** [comment]
Sounds similar to #132. Could you check if this build fixed the issue? https://ci.codemc.io/job/rutgerkok/job/BlockLocker/54/

If yes, then I'll release that build to spigotmc.org.
