### ISSUE TITLE
HOPPERS NOT WORK

### ISSUE THREAD

**Issue by kurkinsnetwork** [rutgerkok/BlockLocker#136]
LOCKED CHEST NOT WORK HOPPERS PLS FİX İT

**Comment by rutgerkok** [comment]
From the [Frequently Asked Questions](https://www.spigotmc.org/resources/blocklocker.3268/):

> **Hoppers cannot put items into/take items from protected chests. How can I fix this?**
> Add a line with the text [Redstone] or [Everyone] to the sign.
