### ISSUE TITLE
API add more feature(Ideas)

### ISSUE THREAD

**Issue by Kokored7214** [rutgerkok/BlockLocker#137]
Hey author! Can you add some more feature to the blocklocker api?
Here is what i wants(or maybe suggest):
- LockAccessEvent
> when player trying to access a lock, execute this event.
> developer can use this event to control that player can open the chest or not.
> and also set the error message?

**Comment by rutgerkok** [comment]
For the record, other plugins can also listen to the PlayerInteractEvent, and interact with BlockLocker through the normal event system.

* To block access to a chest, listen at LOW priority and cancel the event.
* To allow access to a locked chest, listen at HIGH priority and un-cancel the event. The only disadvantage is that the "denied access"-message is already sent at this point.

Other alternatives might include granting the player the `blocklocker.bypass` permission node (this can be done from a plugin) or to hook into the group system of BlockLocker (see README file).
