### ISSUE TITLE
Damaged Anvil's can't be locked

### ISSUE THREAD

**Issue by ConfuseN** [rutgerkok/BlockLocker#14]
When an Anvil is damaged, you can no longer block it. I also tried manually adding both CHIPPED_ANVIL and DAMAGED_ANVIL in the config, but can't get it to work on damaged anvils still

**Comment by rutgerkok** [comment]
Should now be fixed, thanks for reporting!

You can download a dev build here: https://www.dropbox.com/s/obfkwi8u4hhozzj/BlockLocker.jar?dl=0
