### ISSUE TITLE
Selling items in private chest?

### ISSUE THREAD

**Issue by xsorencoolx** [rutgerkok/BlockLocker#145]
hello i found that people with https://bg-software.com/wildtools/ this plugin in my server can sell items in chest please fix it

**Comment by rutgerkok** [comment]
Sorry, missed this issue.

For the record: for shop plugins, its up to them to check whether players have access to a chest. They can fire a PlayerInteractEvent themselves to test whether a player has access. In that way, all chest protection plugins are supported at once.
