### ISSUE TITLE
Players can mine the signs of locked blocks and disable the lock

### ISSUE THREAD

**Issue by ChenyangLT** [rutgerkok/BlockLocker#154]
When I used this plugin on my server, the block lock function worked fine, but players seemed to be able to sneak around and dig for signs.  After digging, locks on chests and so on would not work
![plugins2](https://user-images.githubusercontent.com/123148556/213636194-c3cc8956-070b-4e04-ab99-e3e93e0df06c.png)

https://user-images.githubusercontent.com/123148556/213637105-33f9a84f-81aa-4b98-916e-6999898e62a3.mp4

![plugins](https://user-images.githubusercontent.com/123148556/213637164-b12b7b9f-e49e-4d1a-a19e-fcd337747f8e.png)

**Comment by chappzach24** [comment]
Fix yet?

**Comment by AngelCatOwO** [comment]
In version 1.11, do not use the "blocklocker.edit" permission for player
it is for admin !

**Comment by rutgerkok** [comment]
I've now renamed the permission node to `blocklocker.admin` - should be a bit less confusing. 🙂
