### ISSUE TITLE
 Edit : I won't use the plugin but code mine

### ISSUE THREAD

**Issue by WarnDa** [rutgerkok/BlockLocker#157]
Edit : I won't use the plugin but code mine

**Comment by rutgerkok** [comment]
Sorry, but I'm not going to add this myself.

> I'm still maintaining this plugin, but I've decided to no longer add features myself that I'm not personally interested in. If you would like a new feature, code it yourself! (Or ask someone else to code it for you.) Once you're done, a pull request on Github would be very much appreciated! :)
