### ISSUE TITLE
[Bug] Variable {project.name} doesn't show in the manual update event

### ISSUE THREAD

**Issue by PetyXbron** [rutgerkok/BlockLocker#158]
Hey @rutgerkok, I found a code bug!
This is a screenshot of "update alert": (called "`update_available`" in translations files under "`updater`" property and also called "`MANUAL_UPDATE`" as a Java case in the code - [**UpdateNotifier.java**](https://github.com/rutgerkok/BlockLocker/blob/6b6c73a58ae48873bd04da3ccfe1e922b5d115a8/src/main/java/nl/rutgerkok/blocklocker/impl/updater/UpdateNotifier.java) and it may have connections with [**Translator.java**](https://github.com/rutgerkok/BlockLocker/blob/6b6c73a58ae48873bd04da3ccfe1e922b5d115a8/src/main/java/nl/rutgerkok/blocklocker/Translator.java)).
![image](https://user-images.githubusercontent.com/35902119/229593116-8bacc8b4-60c7-4d19-b691-7a09b0fe3ed1.png)
**Notice:** Because the official Czech language (used in the screenshot) was implemented in this new update ([v1.12](https://github.com/rutgerkok/BlockLocker/releases/tag/v1.12)) this bug may be caused because of the manual translations file import but I guess the variable project.name should replace in messages from translations automatically from any translations file.
Unfortunately, I have absolute non-experience with Java, so if this is an issue I can't create a pull request with the bug fix.

**Comment by rutgerkok** [comment]
This placeholder is normally replaced by "BlockLocker" upon compilation of BlockLocker. So the JAR file you download should already have that text replaced.

I quickly downloaded the JAR file from Spigotmc.org, and in there the translation is indeed already replaced. So if you set `languageFile: translations-cs.yml` in the config.yml of BlockLocker, you should get the correct file.

Maybe you could give me the steps to reproduce? So where should I download BlockLocker from, and what should I set in the config.yml?

**Comment by PetyXbron** [comment]
Yes, the bug was probably made by the fact, that my language file was not from the plugin because it was uploaded from my computer.
