### ISSUE TITLE
[Everyone] unable to bypass protection plugins

### ISSUE THREAD

**Issue by baailey** [rutgerkok/BlockLocker#165]
Hi, in 1.19 my players were able to use thee [Everyone] tag to allow players to access chests within their WorldGuard regions, without any sort of WorldGuard flag granting them access. In 1.20, that is no longer the case.

Is this a bug, or was this never the case in the first place and I'm misremembering?

**Comment by rutgerkok** [comment]
BlockLocker can prevent access to a chest, but it shouldn't give you access if some other plugin (WorldGuard) already blocked it. So you'll need to give the players access through WorldGuard too. No idea if/how that worked in the past.

**Comment by baailey** [comment]
But wouldn’t it make sense for the [Everyone] tag to literally allow anyone access, even if there is a 3rd party plugin like WorldGuard protecting it?

**Comment by rutgerkok** [comment]
It would make sense as an option, but I'm not going to add it myself. (I'm still keeping this plugin updated, but I'm not adding more features myself. Pull requests are always welcome, though.)
