### ISSUE TITLE
Plugin not working 1.20.1?

### ISSUE THREAD

**Issue by Vasegaard** [rutgerkok/BlockLocker#167]
When I try to place a sign on a chest (or door, etc.) it just disapears. It does give me the message that the chest is protected, however it isn't.
Server: Paper(56) 1.20.1-R0.1-SNAPSHOT
plugin 1.12.1
![2023-06-28_22 07 08](https://github.com/rutgerkok/BlockLocker/assets/138060304/11a91442-5a6b-4c8d-9c2e-3a3a57cb64b9)

**Comment by rutgerkok** [comment]
Strange, for me the plugin is working fine. Running Paper version git-Paper-60 (MC: 1.20.1).

Is there anything in the server console around the moment when you tried to place the sign?

**Comment by Stabrinai** [comment]
If you have the CMI plugin installed. 
Please give the player the following permissions:
`cmi.signs.shiftedit`
