### ISSUE TITLE
Hoppers taking items out of private chests

### ISSUE THREAD

**Issue by TheMightyCat** [rutgerkok/BlockLocker#17]
The stuff in a private chest can be easily stolen by using a hopper to transfer the items to another chest. Please fix it.

**Comment by rutgerkok** [comment]
Cannot reproduce. I just attached a hopper to a chest and the items stayed in the chest.

Did you add `[Everyone]` or `[Redstone]` to the sign?

**Comment by rutgerkok** [comment]
Closing this, in hindsight I assume that this is just another case of https://www.spigotmc.org/threads/blocklocker.44937/page-13#post-3545164 . I've added this bug to the FAQ on the main page of the plugin.
