### ISSUE TITLE
se puede robar con tolvas 

### ISSUE THREAD

**Issue by Karen-mtz21** [rutgerkok/BlockLocker#171]
los usurios pueden robar los cofre protegiudos colocandole una tolva

**Comment by rutgerkok** [comment]
Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
>  This isn't caused by BlockLocker, but it's caused by setting hopper.disable-move-event to true in your paper-global.yml file (in the config folder). If this is set to true, then plugins cannot react to item movement in hoppers anymore. So you need to set this to false, there is no other workaround.
