### ISSUE TITLE
Disable hopper check [ Feature request ]

### ISSUE THREAD

**Issue by 7hatGuyAJ** [rutgerkok/BlockLocker#173]
This plugin uses a huge amount of resources (for me) while preventing the placement of hoppers and I would really like to be able to disable this feature. Currently the only way to do this is by setting hopper.disable-move-event to true in the paper-global.yml file (in the config folder).  This is not a feasible option because it prevents other plugins using this event.

**Comment by rutgerkok** [comment]
With a bit of luck, this is no longer needed as of version 1.12.2, as that version contains further optimizations to hoppers.
