### ISSUE TITLE
Automatically Protected Blocks

### ISSUE THREAD

**Issue by JasdanVM** [rutgerkok/BlockLocker#179]
Since any block can be protected, I would like a feature to protect every block of a specified list by default, without the user having to place a sign, examples would include Iron Blocks and Netherite Blocks, so players can make private rooms with no way to get in (as opposed to just protecting the door), or display certain valuable blocks, without having to place a sign over them, this feature could be SHIFT "sensitive", based on permissions, and manually toggled on/off for each player with a command.

**Comment by rutgerkok** [comment]
Doesn't really fit with the plugin unfortunately. It's a sign protection plugin after all, so protecting blocks using other means is outside the scope.
