### ISSUE TITLE
Hopper and the Containers

### ISSUE THREAD

**Issue by JeSuisTrolls** [rutgerkok/BlockLocker#182]
Hi when we put a Container with a private connected to a hopper, the hopper no longer transfers the items into the Containers
![image_2024-01-22_185210356](https://github.com/rutgerkok/BlockLocker/assets/105175788/03e700fb-8002-463a-8a71-723b85ab0e82)
![image_2024-01-22_185217650](https://github.com/rutgerkok/BlockLocker/assets/105175788/4497537e-c14c-4a9a-a71f-4d5afc65dddc)
![image_2024-01-22_185223767](https://github.com/rutgerkok/BlockLocker/assets/105175788/1e6b3e77-1ddd-4f35-99e9-7e9a9ba2648c)

**Comment by rutgerkok** [comment]
This is intended. To allow access for hoppers (and other redstone devices), add [Redstone] to the sign.
