### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by matipoirierg** [rutgerkok/BlockLocker#188]
https://spark.lucko.me/YEpFJkDKlI

**Comment by rutgerkok** [comment]
Ah, the infamous InventoryMoveItemEvent. Could you maybe test whether the latest dev build fixes this?

https://ci.codemc.io/view/Author/job/rutgerkok/job/BlockLocker/82/

This build contains a fix by @Ghost-chu that should optimize hoppers.
