### ISSUE TITLE
BlockLocker incompatible with future versions of Paper

### ISSUE THREAD

**Issue by BangXi** [rutgerkok/BlockLocker#190]
https://paste.gg/p/anonymous/a3841935596c4751b2ec0a4a1bf9a76e

https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955

**Comment by rutgerkok** [comment]
Not sure what exactly caused this, but at least the version that I released today doesn't have this issue. (I didn't make any changes to the code!)

**Comment by BangXi** [comment]
anyway，The version released today，BlockLocker v1.12.2
Tested and working fine❤️
