### ISSUE TITLE
Plugin does not work with SimpleClan clan tags

### ISSUE THREAD

**Issue by IasonKalaitzakis** [rutgerkok/BlockLocker#192]
The plugin used to work with clan tags from SimpleClans about a year~ ago iirc, but it no longer does. Would love if that can be looked into, thanks :)

https://www.spigotmc.org/resources/simpleclans.71242/

**Comment by rutgerkok** [comment]
Still seems to be working on my side... I'm using Paper 1.20.5, BlockLocker 1.12.2 and SimpleClans 2.19.2. I can still access this chest:

![afbeelding](https://github.com/rutgerkok/BlockLocker/assets/1462188/76151b73-5c76-4816-8d4b-6ed1bd37d3db)

**Comment by IasonasKalaitzakis** [comment]
After further testing, I figured it out. It works with the clan NAME, but not the clan tag. Seems a bit counter intuitive, since most clan's names do not fit in signs. However I am not sure if this is this plugin's fault or SimpleClans.
