### ISSUE TITLE
Hopper transfer won't happen when a chest is locked using [Private]

### ISSUE THREAD

**Issue by kcw0205** [rutgerkok/BlockLocker#196]
Hi, so it seems like chests with [Private] signs on them does NOT allow
hopper transfer when the hopper is locked... its complicated to explain but ill provide pictures of 
**when it is not transferring using hopper.**

<img width="491" alt="스크린샷 2024-06-11 오전 9 50 23" src="https://github.com/rutgerkok/BlockLocker/assets/50742278/ad9fc378-0a29-4f36-87ac-306c347767db">
<img width="388" alt="스크린샷 2024-06-11 오전 9 52 22" src="https://github.com/rutgerkok/BlockLocker/assets/50742278/acabb605-6a4e-4cc1-bc07-55e20322027c">

**Comment by rutgerkok** [comment]
If you add [Redstone] to the sign, it should work again. 🙂
