### ISSUE TITLE
Regardless of config, players can lock doors.

### ISSUE THREAD

**Issue by godsyn** [rutgerkok/BlockLocker#2]
I've tried:
```
protectableDoors:
- -WOODEN_DOOR
- -IRON_DOOR_BLOCK
- -SPRUCE_DOOR
- -BIRCH_DOOR
- -JUNGLE_DOOR
- -ACACIA_DOOR
- -DARK_OAK_DOOR

```
and
```
protectableDoors:
```
and just commenting it all out, yet nothing seems to prevent players from protecting doors. They can simply write "private" on their sign after slapping it on a door.

Version 1.2.0 on 
```
This server is running CraftBukkit version git-Spigot-23e921f-8b69bdd (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
```

**Comment by rutgerkok** [comment]
`protectableDoors: []` should work. The minus sign in `-WOODEN_DOOR` seems to be ignored, so

```yaml
protectableDoors:
- -WOODEN_DOOR
- -IRON_DOOR_BLOCK
- -SPRUCE_DOOR
- -BIRCH_DOOR
- -JUNGLE_DOOR
- -ACACIA_DOOR
- -DARK_OAK_DOOR
```
is exactly the same as
```yaml
protectableDoors:
- WOODEN_DOOR
- IRON_DOOR_BLOCK
- SPRUCE_DOOR
- BIRCH_DOOR
- JUNGLE_DOOR
- ACACIA_DOOR
- DARK_OAK_DOOR
```

`protectableDoors:` is just a setting without a value, so it is ignored completely and BlockLocker just uses the default value. In other words, `protectableDoors:` is equivalent to

```yaml
protectableDoors:
- WOODEN_DOOR
- IRON_DOOR_BLOCK
- SPRUCE_DOOR
- BIRCH_DOOR
- JUNGLE_DOOR
- ACACIA_DOOR
- DARK_OAK_DOOR
```

So, `protectableDoors: []` is the only thing that will work.

**Comment by godsyn** [comment]
Much appreciated.
