### ISSUE TITLE
Console UUID Error

### ISSUE THREAD

**Issue by LukeSmith5853** [rutgerkok/BlockLocker#20]
I'm getting this through console
Any idea?

05.04 21:04:39 [Server] INFO WillDraw4Coffee issued server command: /blocklocker 3 WeirdYisThing
05.04 21:04:40 [Server] WARN [BlockLocker] Error fetching UUIDs
05.04 21:04:40 [Server] INFO java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.mojang.com/profiles/minecraft
05.04 21:04:40 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_191]
05.04 21:04:40 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
05.04 21:04:40 [Server] INFO at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_191]
05.04 21:04:40 [Server] INFO at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler$MojangWeb.uuidLookup(UUIDHandler.java:114) ~[?:?]
05.04 21:04:40 [Server] INFO at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler.fetchUniqueIdsAtMojang(UUIDHandler.java:409) ~[?:?]
05.04 21:04:40 [Server] INFO at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler.lambda$fetchUniqueIdsOnlineMode$0(UUIDHandler.java:473) ~[?:?]
05.04 21:04:40 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
05.04 21:04:40 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
05.04 21:04:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
05.04 21:04:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
05.04 21:04:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by rutgerkok** [comment]
If this happens once, you can ignore it - it may be an issue on Mojang's side. If this continues happening, then we'll need to take a further look.

**Comment by rutgerkok** [comment]
I assume that this was just a temporary outage on Mojang's servers, so nothing to fix here for BlockLocker.
