### ISSUE TITLE
Hopper Issue

### ISSUE THREAD

**Issue by ryanrco** [rutgerkok/BlockLocker#204]
We're having an issue on our server where players untrusted to a chest are able to place hoppers below the Chest and retrieve the items.

**Comment by rutgerkok** [comment]
A bit late, but likely its this issue again, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/).

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
> This isn't caused by BlockLocker, but it's caused by setting `hopper.disable-move-event` to `true` in your paper.yml file. If you set it back to `false`, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.
