### ISSUE TITLE
No problem, possible idea

### ISSUE THREAD

**Issue by TheCiROMG** [rutgerkok/BlockLocker#205]
That every time it breaks, the text of a sign is changed, among others, it is recorded in a log file of the 

SECONDS - MINUTES - HOURS - DAY - MONTH - YEAR

To see if a vulnerability is found, among other things

(Possible theft of items on survival servers, this can save lives)

**Comment by rutgerkok** [comment]
To be honest, this sounds like the job for a block logging plugin, like CoreProtect, LogBlock or PrismRefracted.
