### ISSUE TITLE
Open doors by rightclicking interactable non-door blocks

### ISSUE THREAD

**Issue by Boy0000** [rutgerkok/BlockLocker#208]
Seems that if you have a door and a block-entity next to each-other and ontop of a privated block
Right clicking the block-entity will open the door even if said block is not a door

https://github.com/user-attachments/assets/7ffd0e08-b761-4d38-b6d6-0d9d0decfe45

**Comment by rutgerkok** [comment]
Thanks, this should no longer happen in the latest release!
