### ISSUE TITLE
[1.13.2] Others able to bypass sign protected doors

### ISSUE THREAD

**Issue by SalemKitkat** [rutgerkok/BlockLocker#26]
Cause is unknown.

Server IS cracked. (1.13.2 paper)

Current plugin list: http://prntscr.com/oj1qya

Repeatable with wooden doors/trapdoors - Replacing sign manually (without original names on them, only mine) seems to allow it to function as normal.

**Comment by rutgerkok** [comment]
This does not happen on the default settings on a server without any other plugin. So either some setting or some other plugin makes this issue appear.

Could you investigate what is making the issue appear exactly? Then I have something that I can work with. I don't want to spend too much time maintaining this plugin, so I'm asking you to do some more research here.

**Comment by SalemKitkat** [comment]
I will investigate tomorrow and will return a comment here with any findings
