### ISSUE TITLE
Anyone can Break sign I locked it

### ISSUE THREAD

**Issue by BlackKiller04** [rutgerkok/BlockLocker#29]
Hi. In our Server anyone can break the sign i dont know why so i need some help .Thank you

**Comment by rutgerkok** [comment]
Can have multiple causes.

* You made all your friends OP.
* A plugin conflict. Try BlockLocker on a server without any plugins. Slowly add back the plugins until the issue appears. Then we can see which plugin is causing it.
* You might be running the wrong version of BlockLocker for your Minecraft server. See "Are old Minecraft versions supported?" at https://www.spigotmc.org/resources/blocklocker.3268/ .

Make sure to check your console for any errors or warnings.
