### ISSUE TITLE
[Enhancement] Allow signs to be placed under or adjacent to items and over the top of doors unprotected

### ISSUE THREAD

**Issue by groovybluedog** [rutgerkok/BlockLocker#3]
The only thing that other protection plugins do right is the ability to put signs in more places. I would really like to see this come to Blocklocker.

I mostly mean being able to put signs underneath, either directly or one block down to hide signs, and to be able to put signs next to doors (left and right) rather than being forced to go above. 

On top of this I would love to see the ability to place non-BL signs anywhere. As in, if I put the name of a building above the door, BL will cancel the sign because it isn't a protection and will drop the sign. This isn't good behaviour for users who want to label rooms/doors above, without protection.

**Comment by rutgerkok** [comment]
The second point ("the ability to place non-BL signs anywhere") is already done, and will be in the next release.

For you, I have added the ability to attach signs to the blocks left and right of a door.

You can download an updated version of BlockLocker [here](https://dl.dropboxusercontent.com/u/23288978/BlockLocker.jar). 

Placing signs below the block is not possible. The plugin currently looks on which block the sign is attached on, and then decides whether this block is part of a protection. For signs below a protection, this method no longer holds. Of course, I can rework the plugin, but this requires quite a bit of effort. It will also be more taxing on the server, as there are now more locations to look for signs.

I'm just wondering, when you are talking about other protection plugins, which plugin do you mean? As far as I know, Lockette doesn't do this, and I'm not aware of any other updated plugin that works with the [Private] signs. If another plugin exists, I would like to try it out myself, see how it stores UUIDs, etc.

**Comment by groovybluedog** [comment]
Absolutely respect to you for your prompt response and custom resolution. I can't do much at the moment but when my clan grows and have made is very clear that once donations cover site expenses, they get given to small developers like yourself. Where may I donate to?

If I recall correctly, Lockette allows you to place signs underneath doors even with a block in the way (I.e. door at 50 and 51 but sign at 48 with block in the way at 49). It might of changed but I'm pretty damn sure it has done this behaviour in the past even if not now.

I think a plugin called Remote Redstone or something similar does the same where I could place a sign in the example above with a block between the door and the sign and the redstone would activate when the linked sign is activated :3

**Comment by rutgerkok** [comment]
This has finally been added (BlockLocker 1.4). There's now a list called `protectableAttachables` in the configuration file, and for the blocks listed there signs can be attached on more places.
