### ISSUE TITLE
Stealing with minecart hoppers works

### ISSUE THREAD

**Issue by Predavanje** [rutgerkok/BlockLocker#31]
On 1.14.4 paper with the latest blovklocker, stealing items from protected chest using minecart hopper is possible. 
![Screenshot from 2019-08-23 19-46-06](https://user-images.githubusercontent.com/46409712/63612573-d47ec480-c5de-11e9-8436-10112dc8f5d2.png)

**Comment by rutgerkok** [comment]
Make sure `hopper.disable-move-event` is set to `false` in your paper.yml, otherwise Paper will not inform BlockLocker when a hopper moves an item.

Please let me know here whether that solves the issue.

**Comment by key1313** [comment]
I know I am not the OP, but I had the same issue on my server and your solution seems to have resolved my issue. Thanks a bunch!

**Comment by Predavanje** [comment]
Sorry for the late answer. This resolved issue on my server.

**Comment by rutgerkok** [comment]
Happy to hear that.
