### ISSUE TITLE
Repo is 403 Forbidden

### ISSUE THREAD

**Issue by Ugleh** [rutgerkok/BlockLocker#32]
I can not add the repo to my project.
http://www.rutgerkok.nl/repo/

**Comment by rutgerkok** [comment]
Yeah, it's not a proper repo with an index or anything. Does downloading specific files (for example https://www.rutgerkok.nl/repo/nl/rutgerkok/blocklocker/0.1/blocklocker-0.1.jar ) still work?

**Comment by Ugleh** [comment]
Yea, I ended up just doing a system scope.
