### ISSUE TITLE
Doesn't work with server optimalizations.

### ISSUE THREAD

**Issue by SimplyMerlin** [rutgerkok/BlockLocker#37]
Hey, PaperSpigot has a custom redstone engine, and the plugin doesn't seem to be working with that. Could you look into this? Thanks.

(Also if i disable hopper move event, it also doesn't work. I'm guessing this can't be fixed but could you also look in to that? Thanks)

**Comment by sgdc3** [comment]
> (Also if i disable hopper move event, it also doesn't work. I'm guessing this can't be fixed but could you also look in to that? Thanks)

Can't be fixed

**Comment by rutgerkok** [comment]
Exactly, this cannot be fixed. The whole point of that setting in Paper is to stop plugins from acting on hoppers...
