### ISSUE TITLE
Disable protection in certains worlds

### ISSUE THREAD

**Issue by Alex-Roux** [rutgerkok/BlockLocker#39]
Hello
I'm wondering if the plugin could be configured to be disabled on certain worlds i.e. i want the protection in survival world but not in factions.
Thanks

**Comment by rutgerkok** [comment]
Yes, for this you need to negate the permission node `blocklocker.protect` in those certain worlds. Your permissions plugin should be able to do this.

**Comment by Alex-Roux** [comment]
Ok.
Thanks !
