### ISSUE TITLE
Bug when trying to open an iron door

### ISSUE THREAD

**Issue by TheSamux** [rutgerkok/BlockLocker#4]
Hey.
Actually we're having a bug in the 1.11 version, when you try to open an iron door with right click that was previously locked the action repeats 2 times making imposible to open a door.

[http://image.prntscr.com/image/6d6542f609194c8090e87acff0d521c0.png](url)

We've tryed in 1.10 and that error didnt happens so we bet is an actually problem of 1.11 and your plugin.

**Comment by rutgerkok** [comment]
Interesting, let's see if I can fix this.

**Comment by WonderDave** [comment]
I'm experiencing this issue as well, although it seems that the whether or not an iron door opens depends on the type of item/block being held in the player's hand.

**Comment by rutgerkok** [comment]
Should now be fixed.

https://github.com/rutgerkok/BlockLocker/releases/tag/v1.3.1
