### ISSUE TITLE
Able to take off anyones lock with sticky pistons

### ISSUE THREAD

**Issue by kenace87** [rutgerkok/BlockLocker#41]
A sticky piston seems to be able to remove a lock that is on a block.
upon retracting it will  move the block and break the lock.

[image here](https://imgur.com/a/q7NxWda)

**Comment by rutgerkok** [comment]
Thanks for reporting, should now be fixed.

Here's an updated version, if you want to test it: https://www.dropbox.com/s/2e30w0oazij3jhy/BlockLocker.jar?dl=0
