### ISSUE TITLE
Redstone tag not working

### ISSUE THREAD

**Issue by RanokES** [rutgerkok/BlockLocker#42]
### What are you trying to do ?

Blocking a hopper from taking objects inside a chest.

### What is the actual behavior ?

With or without the tag [Redstone] every time I place a hopper under or above a chest it takes all the items inside it.

### How to reproduce the bug ?

1. Place a chest with the BlockLocker protection.
2. Put some objects inside the chest.
3. Place a hopper under the chest, u will see them moving to the chest.

## Environment specifications

- Operating system : Linux

- Java version : 8

- Server version : 1.14.4 (PaperSpigot)

- Blocklocker version : 1.7

**Comment by rutgerkok** [comment]
Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
> This isn't caused by BlockLocker, but it's caused by setting hopper.disable-move-event to true in your paper.yml file. If you set it back to false, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.

**Comment by RanokES** [comment]
Oh, didn't see that and I've check all the FAQ, sorry for the inconvenience and your time :s
