### ISSUE TITLE
plugin version 1.5.0

### ISSUE THREAD

**Issue by kenace87** [rutgerkok/BlockLocker#43]
As per previous bug report.
Fix on issue [#41](https://github.com/rutgerkok/BlockLocker/issues/41) 

Seems version of this plugin for 1.13 wasn't fixed.
Is it possible to release a fix for version 1.5.0
or add API support for 1.13 and 1.14 ?

**Comment by rutgerkok** [comment]
Minecraft 1.13 is already two versions behind, so I'm not going to do this.
