### ISSUE TITLE
Error with hoppers

### ISSUE THREAD

**Issue by dpatrongomez** [rutgerkok/BlockLocker#45]
Hoppers do not fill chest protected by the sign.

Thanks for your plugin

**Comment by rutgerkok** [comment]
Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers cannot put items into/take items from protected chests. How can I fix this?**
> Add a line with the text `[Redstone]` or `[Everyone]` to the sign.
