### ISSUE TITLE
translation french

### ISSUE THREAD

**Issue by playfrite** [rutgerkok/BlockLocker#46]
Hello,

when I translate the plugin into French. The characters' are not accepted.

What should I do?
thank you

**Comment by rutgerkok** [comment]
Hmm, for me special characters like ï work fine. Make sure that your file is saved with the encoding UTF-8.

**Comment by playfrite** [comment]
I have a problem with characters  **'** 

it's the accent

**Comment by rutgerkok** [comment]
Oh, that's because of how the yml files work. If you use a ' somewhere, you must enclose the surrounding text with two ". So like this: 

```yaml
some_setting: "Bob's house"
```

**Comment by playfrite** [comment]
It does not work. The file returns to the original state when I change the 'to "

**Comment by rutgerkok** [comment]
Could you upload your translation file? For me, a `'` works fine, as long as it appears like in the example in my previous post.

**Comment by playfrite** [comment]
[https://www.mediafire.com/file/s22qghwadv8s1jf/translations-en.yml/file](url)

**Comment by rutgerkok** [comment]
Ah, the issue here is that the surrounding text was already enclosed by `'`. Two options to fix this:

```yaml
  cannot_change_sign: '&4 Vous ne pouvez pas changer un panneau à proximité d\'un conteneur
    revendiqué.'
```

(note the `\` before the `'` in `d\'un`)

or:

```yaml
  cannot_change_sign: "&4 Vous ne pouvez pas changer un panneau à proximité d'un conteneur
    revendiqué."
```

(note the double quotation marks around the text)

**Comment by rutgerkok** [comment]
Assuming this is fixed - if not, please leave a message here.
