### ISSUE TITLE
Hoppers Bypass Private Chests

### ISSUE THREAD

**Issue by bartyrealms** [rutgerkok/BlockLocker#47]
Hoppers can be used to drain private'd chests.

Paper-42 (MC 1.15.1)
BlockLocker 1.7.1

**Comment by rutgerkok** [comment]
Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
> This isn't caused by BlockLocker, but it's caused by setting `hopper.disable-move-event` to `true` in your paper.yml file. If you set it back to `false`, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.

**Comment by bartyrealms** [comment]
Yes, I am an idiot.
Thank you.

**Comment by rutgerkok** [comment]
No problem, many people seem to miss this.
