### ISSUE TITLE
I request that you put this translation

### ISSUE THREAD

**Issue by TheCiROMG** [rutgerkok/BlockLocker#52]
Hello, I made a translation into Spanish for this nice and comfortable plugin and I would like you to add it to your GitHub page

The only thing I request is that they give me their credits

a cordial greeting

[translations-es.zip](https://github.com/rutgerkok/BlockLocker/files/4290955/translations-es.zip)

**Comment by rutgerkok** [comment]
Thanks! I added them to the plugin, and they will be included in the next release.
