### ISSUE TITLE
Hopper/hopping minecart can steal stuff

### ISSUE THREAD

**Issue by hkkongou** [rutgerkok/BlockLocker#55]
Hi, love your plugin
very convenient
however, thief in my server use hopper and place it under blocklocker locked chest, the hopper continue export stuff away from the chest, even core protect can't record the exported data and i don't even know how many things did the thief stole from other player's locked chest.

Can you simply add a function to prevent hopper or any kind of rail placing under the chest.

Thank you

**Comment by rutgerkok** [comment]
Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
> This isn't caused by BlockLocker, but it's caused by setting `hopper.disable-move-event` to `true` in your paper.yml file. If you set it back to `false`, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.

**Comment by hkkongou** [comment]
Hi, i have both true and false tested
Hoppers can still steal things away from protected chest.
You can see in the image, the chest is locked, i can't modify it, but when i place the hopper under, is transferring things.
*sorry for late reply
![image](https://user-images.githubusercontent.com/61608872/77131584-071a6e00-6a97-11ea-8702-a1d4c452d524.png)

**Comment by rutgerkok** [comment]
For this chest, you have added `[Redstone]` to the sign, which allows redstone devices (such as hoppers) to access the chest. So if you want to prevent hoppers from stealing items, make sure you don't allow `[Redstone]` to the chest and that `hopper.disable-move-event` is set to `true` .

**Comment by iwaQwQ** [comment]
heya,
it also happened to me :/

i'm on paper 1.15.2 (build 183), latest version of the plugin
it was happening when `hopper.disable-move-event` was set to `true`, changed it to `false` and it worked

**Comment by rutgerkok** [comment]
Assuming this is solved.
