### ISSUE TITLE
Hoppers doesn't work

### ISSUE THREAD

**Issue by kuba150** [rutgerkok/BlockLocker#56]
Hi,
If I didn't place any sing on chest and I have under this chest hopper and put something to chest that hopper destroys itself

I using spigot 1.15.2

**Comment by rutgerkok** [comment]
Sounds like something another plugin is doing - as far as I know BlockLocker doesn't delete blocks.

To rule out that this is caused by another plugin, could you try BlockLocker on a server with no other plugins?

**Comment by kuba150** [comment]
I can't do it but i don't have any other plugin who doing something with blocking hoppers

**Comment by rutgerkok** [comment]
The only place where BlockLocker changing blocks is when placing a sign, so to me it sounds strange that BlockLocker would be causing this. I also asked around on my Minecraft server, and nobody ever saw this.

You can set up a small testing server on your PC/laptop with BlockLocker installed. I don't have the issue myself (hoppers work fine for me) and I don't see what can go wrong in BlockLocker, so I can't help you, sorry.

**Comment by kuba150** [comment]
Ohh ok, maybe worldguard do something with It i will try do something.

Maybe you will add morę than 1 text to lock I mean for example [private] or [lock]

**Comment by rutgerkok** [comment]
You already can, just edit the `translations-en.yml` file and set `private: ['[Private]', '[Lock]']`.

**Comment by kuba150** [comment]
Oh nice thank you ;)
