### ISSUE TITLE
Add command /blocklocker remove

### ISSUE THREAD

**Issue by jere62smi** [rutgerkok/BlockLocker#58]
Hello,

Would it be possible to create an administration command which would remove the protections without having to break them by hand, which would bypass the worldguard access and therefore the person who removes this safe from not being able to take the content. (/blocklocker remove)
Hoping that my suggestion will be taken into account, it would be of great help to me.

**Comment by rutgerkok** [comment]
I don't understand this part of the sentence - ' therefore the person who removes this safe from not being able to take the content' - is there a word missing there? I also don't understand why a server adminstrator wouldn't be able to just bypass WorldGuard too.

**Comment by jere62smi** [comment]
This command would allow certain staff members to allow them to delete [private] without having to go through worldguard. This avoids giving them blocklocker.bypass permission because with it, my staff members have access to all of the content in the safes because I have to give them access to worldguard so that 'it can break the [private]. Quite a few shop plugins provide this kind of administrative command to precisely delete a shop without the person carrying out the order being able to then interact and / or take the content from the trunk.
Sorry if my English is poor and for the late answer, I remain available if ever you still have questions.

**Comment by rutgerkok** [comment]
Do you want the chest to dissappear too, or just the [Private]-sign? And should the item in the chest be dropped on the ground, or should they dissappear too?

**Comment by jere62smi** [comment]
Just a command to pop the [Private] sign.

**Comment by rutgerkok** [comment]
But then your staff still has access to all the content, right? They could just pop off the sign and then steal all the items.

**Comment by jere62smi** [comment]
No, because in my case the people on my staff do not have access to the contents of the safe because worldguard takes over.

**Comment by jere62smi** [comment]
Hello, do you know at once if you are going to develop my request for addition and if so how long will it take?

**Comment by rutgerkok** [comment]
No, it's too specific. It's only useful if you have staff that you cannot trust *and* have two separate chest protection plugins.

**Comment by jere62smi** [comment]
If I develop it myself and provide it to you by pull requests, would you be interested?

**Comment by rutgerkok** [comment]
Yes! From the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/):

> **Can you add this feature?**
> I'm still maintaining this plugin, but I've decided to no longer add features myself that I'm not personally interested in. If you would like a new feature, code it yourself! (Or ask someone else to code it for you.) Once you're done, a pull request on Github would be very much appreciated!
