### ISSUE TITLE
Name changed

### ISSUE THREAD

**Issue by MKMKsGit** [rutgerkok/BlockLocker#59]
My name on the sign had changed to ~<name> and now I can't open it.
But in this server isn't allow a person with a special symbol. I don't know why it changes to that name.
![image](https://user-images.githubusercontent.com/59676467/79300160-211d6400-7f10-11ea-92e4-42ee80a9c31c.png)

**Comment by MKMKsGit** [comment]
![93169861_2950890531624515_7446014909348839424_n](https://user-images.githubusercontent.com/59676467/79300261-6cd00d80-7f10-11ea-8bbc-48f047a6d439.png)

**Comment by rutgerkok** [comment]
This is working as intended, as there is no Minecraft account named MkMks - see https://mcuuid.net/?q=MkMks . (If you are online on the server with that username, it should work. However, the plugin doesn't support cracked servers.)
