### ISSUE TITLE
new feature - unlock key

### ISSUE THREAD

**Issue by DiamondLordGR** [rutgerkok/BlockLocker#62]
Hi I use the block locker plugin on my server
I want to ask if in the foreseeable future you would add an "unlock key". Some kind of block that players could buy or craft and it would brake-bypass the sign lock

**Comment by rutgerkok** [comment]
Something like this already exists in Minecraft: https://www.digminecraft.com/game_commands/add_lock_to_chest.php

(Note: this only works for chests that are not protected by BlockLocker, but are protected by the `Lock` NBT tag.)
