### ISSUE TITLE
Hoppers can retrieve items from protected containers

### ISSUE THREAD

**Issue by FaMa91** [rutgerkok/BlockLocker#66]
Putting an hopper under a chest remove the content, with or without the redstone tag.

**Comment by FaMa91** [comment]
Some more usefull informations:
Latest version (1.7.3)
With 1.7.1 works, so probably a bug introduced with the Hopper cache

**Comment by FaMa91** [comment]
Nevermind, 1.7.1 give me the same problem, probably there is a config with another plugin.

**Comment by rutgerkok** [comment]
Just a quick sanity check, it isn't caused by this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
> This isn't caused by BlockLocker, but it's caused by setting `hopper.disable-move-event` to `true` in your paper.yml file. If you set it back to `false`, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.

**Comment by FaMa91** [comment]
Yes, it was that. I fixed the problem yesterday, thank you.
