### ISSUE TITLE
BIG BUG

### ISSUE THREAD

**Issue by Tomigames** [rutgerkok/BlockLocker#67]
IF someone puts a hopper underneath the protected chest the Items are drained.

**Comment by rutgerkok** [comment]
Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
> This isn't caused by BlockLocker, but it's caused by setting `hopper.disable-move-event` to `true` in your paper.yml file. If you set it back to `false`, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.
