### ISSUE TITLE
Spigot 1.16.1 update

### ISSUE THREAD

**Issue by foxcornn** [rutgerkok/BlockLocker#69]
Will BlockLocker be updated to Spigot 1.16.1 anytime soon? I would love to use it on my server.

**Comment by rutgerkok** [comment]
Is it broken on 1.16.1? I'll have a look this weekend.

**Comment by Aurelien30000** [comment]
Yes, because of NMS :/

**Comment by Aurelien30000** [comment]
@foxcornn You could use my build that works on 1.16, waiting for official support -> https://ufile.io/w20awts8

@rutgerkok If this could helmp you, here are the changes I made for 1.16 support only. Be aware it's just a draft :) https://ufile.io/tqpzqf46

**Comment by foxcornn** [comment]
> @foxcornn You could use my build that works on 1.16, waiting for official support -> https://ufile.io/w20awts8
> 
> @rutgerkok If this could help you, here are the changes I made for 1.16 support only. Be aware it's just a draft :) https://ufile.io/tqpzqf46

Thank you! I will try it out :)

**Comment by rutgerkok** [comment]
Fixed in 1.8.1.
