### ISSUE TITLE
Towny protection

### ISSUE THREAD

**Issue by slvlr** [rutgerkok/BlockLocker#7]
Does this plugin have a feature where you can only lock chests in your towny claimed land (no claiming in wilderness)? If yes how do i use it?
if no can it be added?

**Comment by rutgerkok** [comment]
No, BlockLocker doesn't have such a feature at the moment. I can certainly add it, let's see if I can find some time this weekend.

**Comment by slvlr** [comment]
Hi rutgerkok,

Did you manage to add this feature please?
I want to download this plugin but cannot unless it has it :+1:

**Comment by slvlr** [comment]
Can you upload this version to Spigot please?
Also are there any config changes to enable/disable this or any permissions to bypass?

**Comment by rutgerkok** [comment]
There are no configuration options or permissions at the moment.

I won't upload this version to Spigot yet. This change is not something that needs to be pushed to all servers ASAP, so we can take some time to properly test and polish this feature.

**Comment by rutgerkok** [comment]
I added a permissions check. Now players with the permission node `blocklocker.wilderness` can place chests in the wilderness. This permission node is granted by default, so you need a permissions plugin to remove that permissions node from players.
