### ISSUE TITLE
Opening a chest protected by a scoreboard team causes an error

### ISSUE THREAD

**Issue by jackson-57** [rutgerkok/BlockLocker#74]
Hello, after protecting a container (I used a furnace in this photo) with the following format ('Screw' is the id of the scoreboard team), ![2020-07-12_13 17 07](https://user-images.githubusercontent.com/49173011/87255812-d2b22f80-c442-11ea-9941-3ba054f11ee3.png) I am still able to open the container after leaving the team.

I noticed in the server console that there is a PlayerInteractEvent error every time I open the chest. 
![image](https://user-images.githubusercontent.com/49173011/87255894-887d7e00-c443-11ea-8b2e-595aa8d7efde.png)
I'm running Paper 1.16.1 build #88, and BlockLocker v1.8.1. Please let me know if you need any more info. If you know of any workarounds while this is being fixed, that'd be great to know. Thanks!

edit: /plugins command output: `Plugins (10): BlockLocker, CoreProtect, DiscordSRV, floodgate-bukkit, Geyser-Spigot, Harbor, LuckPerms, PhantomEconomy, QuickShop, Vault`

**Comment by rutgerkok** [comment]
Strange, this is an error happening in Towny code (see the last few lines starting with `com.palmergames`), but Towny doesn't appear on your plugin list. Maybe you have a clue on what's happening?

Otherwise, I can try downloading all those plugins and check if any of them includes part of Towny.

**Comment by jackson-57** [comment]
I'm wondering if [PhantomEconomy](https://www.spigotmc.org/resources/%E2%99%A6-phantomeconomy-%E2%99%A6-for-1-7-1-16.75053/) is causing the issue, as I haven't used it before with BlockLocker and it mentions that it has native support for Towny

**Comment by jackson-57** [comment]
Alright, I just tried putting PhantomEconomy, Vault, and BlockLocker in a clean Paper server and I encountered that error. Removing PhantomEconomy and Vault caused the error to not happen, and I'm unable to open the chest when not in the team.

**Comment by rutgerkok** [comment]
Turns out like PhantomEconomy contains a copy of Towny. This makes BlockLocker assume that Towny is installed, so it crashes. I've created a pull request over there, so hopefully it will be fixed soon.
