### ISSUE TITLE
Hoppers bypass protection

### ISSUE THREAD

**Issue by MrNaspo** [rutgerkok/BlockLocker#75]
Hello. A problem has arisen where other players can still steal from people's locked containers simply by connecting a hopper to it. Is there any way we can fix this? Thanks!

**Comment by rutgerkok** [comment]
Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
> This isn't caused by BlockLocker, but it's caused by setting `hopper.disable-move-event` to `true` in your paper.yml file. If you set it back to `false`, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.

**Comment by MrNaspo** [comment]
Wouldn't that disable hoppers in general throughout the entire server?

**Comment by rutgerkok** [comment]
No, the setting only affects the events that plugins listen to, not the transfers themselves. Besides, you need to have it set to `disable-move-event: false` for BlockLocker to work correctly, so nothing gets disabled.

**Comment by MrNaspo** [comment]
Oh okay. Thank you!
