### ISSUE TITLE
Updated Spanish translation and improved configuration file

### ISSUE THREAD

**Issue by TheCiROMG** [rutgerkok/BlockLocker#80]
Hello again, I bring a slightly improved Spanish translation and with it a configuration file with the new Minecraft 1.16.1 blocks
[Translation and  Config.zip](https://github.com/rutgerkok/BlockLocker/files/5080233/Translation.and.Config.zip)

**Comment by rutgerkok** [comment]
Thanks! The config file was updated earlier in https://github.com/rutgerkok/BlockLocker/commit/e5ec8ab616787c9390cd6bd8e23155b14224dd97 , so I left that part out.
