### ISSUE TITLE
Issue with bungeecord and conflict with using /plugins command

### ISSUE THREAD

**Issue by wearenoobsuk** [rutgerkok/BlockLocker#81]
I have been chasing an issue for a long time, If i type /plugins on my server it kicks me from my survival server back to my fallback server 'hub' and gives an error. If i remove the plugin blocklocker It doesn't do this. It's only happened since updating to 1.16.1. I really hope this can be fixed because I have had this plugin over a year and we have alot of protected chests *thousands* on the network. Thankyou

**Comment by rutgerkok** [comment]
Could you post the error? BlockLocker doesn't do anything with /plugins, so I would be interested to see what is causing the error.

**Comment by wearenoobsuk** [comment]
![chrome_Wh437y9UWv](https://user-images.githubusercontent.com/62724418/90659275-6219e200-e23c-11ea-8c2b-878bd93c5dd9.png)
![javaw_gpL5l5UnBN](https://user-images.githubusercontent.com/62724418/90659277-62b27880-e23c-11ea-8d7b-5c003f0c206c.png)

So this is what happens when i type /plugins or /pl or bukkit:plugins on my survival servers
Note, If i transfer blocklocker onto my none bungee test server it doesn't do this, it only does it on my bungee server.

I'm 100% sure the issue goes away when removing blocklocker

**Comment by wearenoobsuk** [comment]
I'm fully upto date on bungeecord and my jar, Running 1.16.1
