### ISSUE TITLE
Issue with AdvancedChests, duplicate item infinitly.

### ISSUE THREAD

**Issue by Zzheyd** [rutgerkok/BlockLocker#82]
Hi here, we have a problem with AdvancedChests plugin, if private is set in chest, hopper doesnt drop item, but duplicate in chest (sry for my english)

Video its maybe better idea : https://www.youtube.com/watch?v=rY0EpjNlK-4

thanks :)

**Comment by rutgerkok** [comment]
This must be a problem with AdvancedChest. BlockLocker doesn't create or destroy items, it only cancels the transfer if necessary. For reference (for the author of AdvancedChest), here's the entire code that interacts with hoppers.

```java
    @EventHandler(ignoreCancelled = true)
    public void onInventoryMoveItemEvent(InventoryMoveItemEvent event) {
        Block from = getInventoryBlockOrNull(event.getSource());
        if (from != null) {
            if (isProtectedForRedstone(from)) {
                event.setCancelled(true);
                return;
            }
        }
        Block to = getInventoryBlockOrNull(event.getDestination());
        if (to != null) {
            if (isProtectedForRedstone(to)) {
                event.setCancelled(true);
                return;
            }
        }
    }
```

([Rest of the file](https://github.com/rutgerkok/BlockLocker/blob/7b20679230ab0d7edde35c6a08cc6ffdf01e7812/src/main/java/nl/rutgerkok/blocklocker/impl/event/InteractListener.java#L276))
