### ISSUE TITLE
Ability to create player groups for private chest sharing

### ISSUE THREAD

**Issue by JustPugDev** [rutgerkok/BlockLocker#84]
Since there are only two additional lines on a sign to give other players chest access, it is difficult to add a lot of players to a large wall of chests, e.g. A storage system. Instead, add the ability for players to register a group, and add other players to that group. Then using the groups name on a private sign would give every player in that group access to that chest.

This could be implemented with /group create to create a group, group add to add players, /group remove to remove players, and /group delete to delete the group completely. These commands would only be accessible to the original creator of the group.

The motivation for this stems from now having several hundred chests in the world, and the realisation that managing access to all these is becoming difficult when a new player is involved. Simply doing /group add would be sufficient to update the access with the new system.

**Comment by rutgerkok** [comment]
The plugin already supports the group systems of Towny, MassiveCraft, mcMMO, Guilds, vanilla scoreboards and Bukkit permission plugins. Adding more plugins to the list is possible.

But I'm not going to add a group system to BlockLocker itself. It's a block locking plugin after all, so a group system wouldn't fit in there. In addition, a group system would also need, at the bare minimum, overrides for server admins and some way to have multiple people manage a group. For a well-functioning group system, server admins will also want other features, such as chat, land claiming, pvp features, BungeeCord support, etc. Other plugins can do this better.
