### ISSUE TITLE
Custom Inventory Support

### ISSUE THREAD

**Issue by Sn0wStorm** [rutgerkok/BlockLocker#85]
Hi, i'm the developer of [Brewery](https://github.com/DieReicheErethons/Brewery)
i'd like to add BlockLocker support to lock our custom Inventories (Barrels). It would already be possible to check the sign for any locks, but currently when you want to add a private sign to lock it, it just pops off as it detects no lockable container behind it.

So it would be great if there was a hook to tell the plugin if the sign is currently lockable or not, around here:
https://github.com/rutgerkok/BlockLocker/blob/224274f1603d381eb9a4f2042cf94e363bbe9dd7/src/main/java/nl/rutgerkok/blocklocker/impl/event/SignChangeListener.java#L105

Or is there any other way to create a Locked Sign without a chest behind it?

Thank you!

**Comment by rutgerkok** [comment]
You'll need to modify the `plugins/BlockLocker/config.yml` file to add the barrel to the list of blocks.

**Comment by Sn0wStorm** [comment]
My plugin adds more custom barrels, made out of wood blocks. And i don't want all wood blocks to be lockable, only if they are part of a custom barrel

**Comment by rutgerkok** [comment]
Added a simple API for your plugin. Basically:

```java
BlockLockerAPIv2.getPlugin().getChestSettings().getExtraProtectables().add(new ProtectableBlocksSettings() {

            @Override
            public boolean canProtect(Block block) {
                return checkHereForABarrel(block);
            }

            @Override
            public boolean canProtect(ProtectionType type, Block block) {
                if (type != ProtectionType.CONTAINER) return;

                return checkHereForABarrel(block);
            }});
```

If this works for you, I'll update the BlockLocker version on SpigotMC.org.

**Comment by Sn0wStorm** [comment]
This works great, I couldn't have asked for more!

Implemented support for BlockLocker into https://github.com/DieReicheErethons/Brewery/commit/0b9b364f28634a8dff7bb66eb8c3675d747b2eec
Works exactly as i intended! Thank you

**Comment by rutgerkok** [comment]
Great! I've uploaded BlockLocker 1.9 to spigotmc.org.

By the way, you can now also download version 1.9 from the codemc repo.

```xml
<repository>
	<id>codemc-repo</id>
	<url>https://repo.codemc.org/repository/maven-public/</url>
</repository>
```

And:

```xml
<dependency>
	<groupId>nl.rutgerkok</groupId>
	<artifactId>blocklocker</artifactId>
	<version>1.9</version>
	<scope>provided</scope>
</dependency>
```

**Comment by Sn0wStorm** [comment]
In the 1.9 update on Spigot and in the Github Releases, this change is not included for some reason.
The class `nl.rutgerkok.blocklocker.ProtectableBlocksSettings` is missing and also the `.getExtraProtectables()` method.

In the 1.9 on your maven repo everything is fine!

**Comment by rutgerkok** [comment]
Hmm, strange, seems that commit was missing from the release. Well, 1.9.1 to the rescue. Thanks for reporting!
