### ISSUE TITLE
Stealing with hoppers

### ISSUE THREAD

**Issue by thomaboehi** [rutgerkok/BlockLocker#87]
Hi!

I've seen a player who was stealing some chests with Hoppers. I thought it wouldn't work, but it did....

We're running on PaperMC 284
server version 1.16.4

If you need more informations, of course I'll answer

**Comment by rutgerkok** [comment]
Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?

> **Hoppers can put items into/take items from protected chests. How can I fix this?**
> This isn't caused by BlockLocker, but it's caused by setting `hopper.disable-move-event` to `true` in your paper.yml file. If you set it back to `false`, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.

**Comment by thomaboehi** [comment]
It is already set on false...

**Comment by rutgerkok** [comment]
Just tested it again on my server, and BlockLocker 1.9 works fine with hoppers. So I don't know what I could do here.

Is there [Redstone] or [Everyone] on the sign? Maybe another plugin is interfering?

**Comment by Wrooar** [comment]
Hi!

I have the same problem on my server, I'm on 1.16.4 with Paper 323, using the BlockLocker 1.9.1.
hopper.disable-move-event it's on false, and I don't have any other plugin that manage chest.

Thanks.

**Comment by thomaboehi** [comment]
I did nothing, and now it is fixed ^^'
