### ISSUE TITLE
Protection Stones BUG 1.16.4

### ISSUE THREAD

**Issue by TheCiROMG** [rutgerkok/BlockLocker#89]
The matter is easy, hello back.

The error is as follows

A User X puts a Protection Stone, but another User Z can put the protection of the BlockLocker but cannot open it (either chest, oven, etc), is there any way to solve that?

**Comment by rutgerkok** [comment]
What is a Protection Stone? Is that something from another plugin? If another plugin has locked the block, then BlockLocker won't unlock it. Essentially, you end up with two locks on a single chest.

**Comment by TheCiROMG** [comment]
Can't implement that

if I put a chest with blocklocker + username, can he open it ignoring the protection blocks? just open that chest
