### ISSUE TITLE
Cannot add offline player (cracked servers only)

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [rutgerkok/BlockLocker#9]
When i try to add offline player to protection, after a while his nickname changes to "~nickname" and is not working. Is it possible to add to protection someone, who is online?

**Comment by OfficialAndyX** [comment]
I think thats how its intended. When the user comes online and interacts with the chest it will update it.

**Comment by rutgerkok** [comment]
BlockLocker is UUID-based, so it has to look up the UUID for players. When a player is online, BlockLocker simply asks the server what the UUID of the player is. However, when a player is offline, BlockLocker asks mojang.com. If mojang.com cannot be accessed, or if no Mojang account exists with that name, then the lookup will fail.

So in conclusion: if BlockLocker cannot get the Mojang UUID of an account, the account needs to be online. Is that what is happening on your server?

**Comment by sgdc3** [comment]
@Kryniowesegryderiusz is your server online or offline mode?

**Comment by Kryniowesegryderiusz** [comment]
Offline mode, now i see what could be the problem though. Thanks

**Comment by sgdc3** [comment]
No offline mode should be easier to handle, as it doesn't have to ask mojang servers

**Comment by rutgerkok** [comment]
Yes, but supporting only online mode is still easier than supporting both. Especially since online mode support is already there while offline mode support needs to be coded first.

Pull requests are welcome, but I don't have any motivation myself to add support for offline mode.
