### ISSUE TITLE
people cant access chest

### ISSUE THREAD

**Issue by xxclaiire** [rutgerkok/BlockLocker#92]
The plugin was working, but randomly now whenever someone adds a name to a chest, the person can't open it. pleaseee help

**Comment by rutgerkok** [comment]
Is your server in online mode (or behind an online mode Bungee proxy)? If not, then BlockLocker won't work correctly, as it uses Mojang UUIDs.

**Comment by jdoesplay** [comment]
Is this a recent development? We are having the same issue and did not have problems until a few weeks ago. It has caused major issues in our community.

**Comment by xxclaiire** [comment]
> Is your server in online mode (or behind an online mode Bungee proxy)? If not, then BlockLocker won't work correctly, as it uses Mojang UUIDs.

tbh i'm not sure what that means but i use shockbyte as my server provider. it was working originally but not anymore randomly.

**Comment by xxclaiire** [comment]
> Is this a recent development? We are having the same issue and did not have problems until a few weeks ago. It has caused major issues in our community.

yes it is! it was working 2 days ago but now it is not

**Comment by jdoesplay** [comment]
> > Is this a recent development? We are having the same issue and did not have problems until a few weeks ago. It has caused major issues in our community.
> 
> yes it is! it was working 2 days ago but now it is not

Whoops, sorry, my response was to rutgerkok. I should've quoted him. I'm saying I am also having the same issue and it just started pretty recently, so I was curious if this change is support was new.

**Comment by WMGameLive** [comment]
Same issue here. it was working yesterday for my server but now it is broken, only the owner can access the chest.

**Comment by WMGameLive** [comment]
Even if only BlockLocker is installed, the issue still exists, no matter if you use Spigot or Paper.

**Comment by rutgerkok** [comment]
Online mode = server checks online whether each account is a valid Mojang account. Offline mode = no checks, so also pirated copies of Minecraft can login.

BlockLocker is still working fine for me:

![afbeelding](https://user-images.githubusercontent.com/1462188/103571042-7cdab380-4eca-11eb-9256-c3b3a4a8e90b.png)

Using BlockLocker 1.9.1, online mode, git-Paper-386 (MC: 1.16.4).

Is there an error in the console maybe?

**Comment by WMGameLive** [comment]
No any error.
I recorded a video.
https://youtu.be/6mbr0rKyQh0

**Comment by botany111** [comment]
same question
Even if the name is entered on the sign, other players cannot open the box

**Comment by rutgerkok** [comment]
Thanks for reporting! This should be fixed in build 19 - download at https://ci.codemc.io/job/rutgerkok/job/BlockLocker/19/ . I plan to upload this to spigotmc.org tomorrow - I'll test it more extensively on my own server first.
