### ISSUE TITLE
[Redstone] tag doesn't work.

### ISSUE THREAD

**Issue by Gitberham** [rutgerkok/BlockLocker#93]
One of the players on my server pointed out that hoppers do not work even with the [Redstone] tag applied.

I've included a video to showcase the problem:
[https://www.youtube.com/watch?v=OC9A4b1ocRM](url)

The same applies the other way around (Chest on top, hopper on the bottom)

Yes, disable-move-event in paper.yml is set to false.

**Comment by rutgerkok** [comment]
This is likely the same bug as #92. In short: a recent change to Spigot (4 days ago) broke the /blocklocker command. You can download an updated version of BlockLocker at https://ci.codemc.io/job/rutgerkok/job/BlockLocker/19/ . If this build survives my testing, I'll upload it to spigotmc.org tomorrow.
