### ISSUE TITLE
LuckPerms Compatibility Issue?

### ISSUE THREAD

**Issue by Arkane** [rutgerkok/BlockLocker#94]
I currently have luckperms installed as a permissions manager and it seems that blocklocker permissions are completely ignored?

I have essentially two groups, group1 has the permission blocklocker.protect and group2 does not.
However, group2 can still protect chests etc with signs for some reason.

I have no idea how to prevent that from happening, it seems that the permission nodes are completely ignored.

PS: Group 2 does not have any parent groups, it is the default group upon joining the server.

**Comment by rutgerkok** [comment]
The permission `blocklocker.protect` is already set to `true` by default, so you explicitly need to set it to `false` for a group to prevent them from claiming chests.

**Comment by Arkane** [comment]
Thanks for the quick reply!
I've gone ahead and set the permission to false and it works as intended ^^

Have a nice day! 
Thanks again for an amazing plugin.
