### ISSUE TITLE
Minecart with hopper can bypass protection

### ISSUE THREAD

**Issue by ElMoha943** [rutgerkok/BlockLocker#96]
What title says, you can steal things from protected chest using a minecart with a hopper
![image](https://user-images.githubusercontent.com/25410859/105776623-a924a580-5f47-11eb-941d-fdfabab63b6c.png)

**Comment by rutgerkok** [comment]
Just some troubleshooting steps:

* Are you on the latest BlockLocker? Spigot changed how signs are saved, which caused some trouble. Updating BlockLocker fixes it.
* Could it be this, from the [FAQ](https://www.spigotmc.org/resources/blocklocker.3268/)?
  
  > **Hoppers can put items into/take items from protected chests. How can I fix this?**
  > This isn't caused by BlockLocker, but it's caused by setting `hopper.disable-move-event` to `true` in your paper.yml file. If you set it back to `false`, then Paper will again tell plugins when hoppers are moving items, so that BlockLocker can block the item movement.

**Comment by ElMoha943** [comment]
It was the hopper.disable-move-event, sorry for not reading the faq and making you waste time. Thanx for the help!
