### ISSUE TITLE
Suggestion, toggle message

### ISSUE THREAD

**Issue by slvlr** [rutgerkok/BlockLocker#97]
Some players are requesting that I remove the message "Place a sign on this chest to protect it" when placing chests. But I would like to keep that message to inform new players about it. 

Could you make a command to toggle this message? Example /blocklocker togglemessage

Then potentially change,the main message to "Place a sign on this chest to protect it. Type /blocklocker togglemessage to toggle this message."

Thanks!

**Comment by rutgerkok** [comment]
This is not possible with how the plugin is designed. The plugin would need to store somewhere that a player has disabled the message. It would then need some kind of database, which the plugin actively avoids. (If a database isn't a problem, then you could as well use LWC, which has more features.)
